name: "j20 publish"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/j20/**'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:

  "test":
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, '(j20):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: |
          pnpm install
          cd packages/signal
          pnpm test
          pnpm build
          cd ../j20
          pnpm test

  "publish":
    needs: test
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.head_commit.message, 'release(j20):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: |
          pnpm install
          cd packages/signal
          pnpm test
          pnpm build
          cd ../j20
          pnpm build
          pnpm publish --no-git-checks --access public