name: "jsx-transform publish"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/jsx-transform/**'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:

  "test":
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, '(jsx-transform):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: |
          pnpm install
          cd packages/jsx-transform
          pnpm test
          pnpm build

  "publish":
    needs: test
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.head_commit.message, 'release(jsx-transform):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: |
          pnpm install
          cd packages/jsx-transform
          pnpm test
          pnpm build
          pnpm publish --no-git-checks --access public